Repository pingcap/tidb-engine-ext, pull requests merged in 2024-06, with the labels that each got.

#371 Strengthen configuration change approval
  HACKED_OWNERS
  HACKED_OWNERS_ALIASES
  proxy_components/proxy_server/src/HACKED_OWNERS
Labels: do-not-merge/hold, size/S

#373 Add approvers
  .github/workflows/pr-ci.yml
  HACKED_OWNERS_ALIASES
Labels: size/M, approved, lgtm

#375 Fix slog and slog-global
  Cargo.lock
  proxy_components/engine_store_ffi/Cargo.toml
  proxy_components/engine_tiflash/Cargo.toml
  proxy_components/mock-engine-store/Cargo.toml
  proxy_components/proxy_ffi/Cargo.toml
  proxy_components/proxy_server/Cargo.toml
  proxy_components/proxy_test_raftstore_v2/Cargo.toml
  proxy_tests/Cargo.toml
Labels: size/L, approved, lgtm
