Repository pingcap/tidb-engine-ext, pull requests merged in 2024-01, with the labels that each got.

#363 Support cancel fap on TiFlash's side
  proxy_components/engine_store_ffi/src/core/fast_add_peer.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/fap_snapshot.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/mod.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/region.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/snapshot.rs
  proxy_components/engine_tiflash/src/mixed_engine/elementary.rs
  proxy_components/engine_tiflash/src/proxy_utils/cached_region_info_manager.rs
  proxy_components/engine_tiflash/src/proxy_utils/mod.rs
  proxy_components/engine_tiflash/src/proxy_utils/proxy_ext.rs
  proxy_components/mock-engine-store/src/mock_store/mock_engine_store_server.rs
  proxy_components/mock-engine-store/src/mock_store/mock_fast_add_peer_impls.rs
  proxy_components/mock-engine-store/src/mock_store/mock_snapshot_impls.rs
  proxy_components/proxy_ffi/src/engine_store_helper_impls.rs
  proxy_components/proxy_ffi/src/interfaces.rs
  proxy_components/proxy_server/src/config.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_tests/proxy/shared/fast_add_peer/fp.rs
  proxy_tests/proxy/shared/fast_add_peer/mod.rs
  proxy_tests/proxy/shared/fast_add_peer/simple.rs
  proxy_tests/proxy/v2_compat/tablet_snapshot.rs
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/@version
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/ProxyFFI.h
Labels: size/XXL

#364 Pick fn_get_lock_by_key to master
  proxy_components/mock-engine-store/src/mock_store/mock_engine_store_server.rs
  proxy_components/proxy_ffi/src/engine_store_helper_impls.rs
  proxy_components/proxy_ffi/src/interfaces.rs
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/@version
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/ProxyFFI.h
Labels: size/M

#361 FFI: add two empty implement FFI for compatibility
  proxy_components/proxy_ffi/src/encryption_impls.rs
  proxy_components/proxy_ffi/src/interfaces.rs
  proxy_components/proxy_ffi/src/raftstore_proxy_helper_impls.rs
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/@version
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/ProxyFFI.h
Labels: size/M

#365 Make FAP FFIs aware the index and term of an fap snapshot
  proxy_components/engine_store_ffi/src/core/fast_add_peer.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/fap_snapshot.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/region.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/snapshot.rs
  proxy_components/mock-engine-store/src/mock_store/mock_fast_add_peer_impls.rs
  proxy_components/proxy_ffi/src/engine_store_helper_impls.rs
  proxy_components/proxy_ffi/src/interfaces.rs
  proxy_tests/proxy/shared/fast_add_peer/fp.rs
  proxy_tests/proxy/shared/fast_add_peer/simple.rs
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/@version
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/ProxyFFI.h
Labels: size/XL
