Repository pingcap/tidb-engine-ext, pull requests merged in 2024-07, with the labels that each got.

#379 Skip proxy build time
  Makefile
Labels: size/XS, approved, lgtm

#380 Disable enable_heap_profiling and improve some codes
  Cargo.lock
  components/engine_panic/Cargo.toml
  components/engine_rocks/Cargo.toml
  components/engine_traits/Cargo.toml
  components/engine_traits_tests/Cargo.toml
  components/hybrid_engine/Cargo.toml
  components/raft_log_engine/Cargo.toml
  components/range_cache_memory_engine/Cargo.toml
  proxy_components/proxy_ffi/src/jemalloc_utils.rs
  proxy_components/proxy_server/src/config.rs
  proxy_components/proxy_server/src/status_server/mod.rs
  proxy_components/proxy_server/src/status_server/profile.rs
  proxy_components/proxy_server/src/status_server/vendored_utils.rs
  proxy_scripts/ci_check.sh
  proxy_scripts/make_env.sh
  proxy_tests/proxy/shared/mod.rs
  proxy_tests/proxy/shared/pprof_jemalloc.rs
  proxy_tests/proxy/shared/replica_read.rs
  raftstore-proxy-main/Cargo.toml
  raftstore-proxy-main/src/main.rs
Labels: size/L, lgtm

#383 Fix some warnings and errors on mac
  proxy_components/engine_store_ffi/Cargo.toml
  proxy_components/engine_tiflash/Cargo.toml
  proxy_components/mock-engine-store/Cargo.toml
  proxy_components/proxy_ffi/Cargo.toml
  proxy_components/proxy_server/Cargo.toml
  proxy_components/proxy_server/src/status_server/mod.rs
  proxy_components/proxy_server/src/status_server/vendored_utils.rs
Labels: size/XXL, approved, lgtm

#384 Enable /debug/pprof/heap
  proxy_components/proxy_server/src/status_server/jeprof.in
  proxy_components/proxy_server/src/status_server/profile.rs
Labels: size/XXL, approved, lgtm
