Repository pingcap/tidb-engine-ext, pull requests merged in 2025-09, with the labels that each got.

#439 support status server metrics
  Makefile
  proxy_components/proxy_server/src/status_server/mod.rs
Labels: size/M, approved, lgtm

#440 Fix the path label of req is not trim as expected
  proxy_components/proxy_server/src/status_server/mod.rs
Labels: size/M, approved, lgtm

#441 degrade TiKV Error log level for false alarms
  components/concurrency_manager/src/lib.rs
  components/in_memory_engine/src/region_label.rs
  components/pd_client/src/client.rs
  components/pd_client/src/util.rs
  components/raftstore-v2/src/operation/command/write/ingest.rs
  components/raftstore-v2/src/operation/misc.rs
  components/raftstore-v2/src/worker/pd/mod.rs
  components/raftstore-v2/src/worker/pd/store.rs
  components/raftstore/src/compacted_event_sender.rs
  components/raftstore/src/coprocessor/split_observer.rs
  components/raftstore/src/store/entry_storage.rs
  components/raftstore/src/store/fsm/peer.rs
  components/raftstore/src/store/fsm/store.rs
  components/raftstore/src/store/peer.rs
  components/raftstore/src/store/worker/cleanup_snapshot.rs
  components/raftstore/src/store/worker/pd.rs
  components/raftstore/src/store/worker/region.rs
  components/resource_control/src/service.rs
  components/sst_importer/src/sst_importer.rs
  src/server/gc_worker/gc_manager.rs
  src/server/raft_client.rs
  src/server/raft_server.rs
  src/server/raftkv/raft_extension.rs
  src/server/service/batch.rs
  src/server/service/debug.rs
  src/server/service/kv.rs
  src/server/snap.rs
  src/server/tablet_snap.rs
Labels: size/L, approved, lgtm

#442 degrade TiKV Error log level for false alarms(raftstore-proxy-8.5)
  Makefile
  components/engine_panic/Cargo.toml
  components/engine_rocks/Cargo.toml
  components/engine_traits/Cargo.toml
  components/hybrid_engine/Cargo.toml
  components/in_memory_engine/Cargo.toml
  components/in_memory_engine/src/region_label.rs
  components/pd_client/src/client.rs
  components/pd_client/src/util.rs
  components/raft_log_engine/Cargo.toml
  components/raftstore-v2/src/operation/command/write/ingest.rs
  components/raftstore-v2/src/operation/misc.rs
  components/raftstore-v2/src/worker/pd/mod.rs
  components/raftstore-v2/src/worker/pd/store.rs
  components/raftstore/src/compacted_event_sender.rs
  components/raftstore/src/coprocessor/split_observer.rs
  components/raftstore/src/store/entry_storage.rs
  components/raftstore/src/store/fsm/peer.rs
  components/raftstore/src/store/fsm/store.rs
  components/raftstore/src/store/peer.rs
  components/raftstore/src/store/worker/cleanup_snapshot.rs
  components/raftstore/src/store/worker/pd.rs
  components/raftstore/src/store/worker/region.rs
  components/resource_control/src/service.rs
  components/sst_importer/src/sst_importer.rs
  src/server/gc_worker/gc_manager.rs
  src/server/raft_client.rs
  src/server/raft_server.rs
  src/server/raftkv/raft_extension.rs
  src/server/service/batch.rs
  src/server/service/debug.rs
  src/server/service/kv.rs
  src/server/snap.rs
  src/server/tablet_snap.rs
Labels: size/L, approved, lgtm

#444 downgrade some proxy logs (release-8.5)
  proxy_components/engine_store_ffi/src/core/forward_raft/command.rs
Labels: size/XS, approved, lgtm
