Repository pingcap/tidb-engine-ext, pull requests merged in 2025-03, with the labels that each got.

#427 Support replay fap snapshot after it is applied
  proxy_components/engine_store_ffi/src/core/forward_raft/fap_snapshot.rs
  proxy_components/engine_store_ffi/src/core/forward_raft/snapshot.rs
  proxy_tests/proxy/shared/fast_add_peer/fp.rs
Labels: size/L

#431 [release-9.0-beta.1] Cherry-pick tikv#18328
  Cargo.lock
  components/external_storage/Cargo.toml
  components/external_storage/src/local.rs
  components/sst_importer/src/sst_importer.rs
  tests/failpoints/cases/test_import_service.rs
Labels: size/L, approved, lgtm

#429 Fix safe ts not updated
  proxy_components/engine_store_ffi/src/observer.rs
  proxy_components/mock-engine-store/src/mock_cluster/cluster_ext.rs
  proxy_components/mock-engine-store/src/mock_cluster/v1/node.rs
  proxy_components/mock-engine-store/src/mock_cluster/v1/server.rs
  proxy_components/mock-engine-store/src/mock_store/mock_engine_store_server.rs
  proxy_components/proxy_server/src/run.rs
  proxy_tests/proxy/shared/server_cluster_test.rs
  proxy_tests/proxy/utils/v1_server.rs
Labels: size/XL, approved, lgtm
