Repository pingcap/tidb-engine-ext, pull requests merged in 2025-01, with the labels that each got.

#408 Limit proxy's memory from TiFlash's side
  proxy_components/proxy_server/src/config.rs
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_tests/proxy/shared/config.rs
  proxy_tests/proxy/shared/store.rs
Labels: size/L, lgtm

#417 Adapt to TiKV's raft grpc message filter
  Cargo.lock
  Cargo.toml
  components/batch-system/src/batch.rs
  components/raftstore/src/store/fsm/peer.rs
  components/resource_control/src/metrics.rs
  components/server/src/server.rs
  components/server/src/server2.rs
  components/test_raftstore-v2/src/server.rs
  components/test_raftstore/src/cluster.rs
  components/test_raftstore/src/server.rs
  components/test_raftstore/src/util.rs
  components/tidb_query_datatype/src/codec/mysql/time/mod.rs
  components/tidb_query_expr/src/impl_time.rs
  components/tidb_query_expr/src/lib.rs
  components/tikv_util/src/sys/thread.rs
  components/tikv_util/src/yatp_pool/metrics.rs
  components/tracker/src/lib.rs
  components/txn_types/src/lock.rs
  etc/config-template.toml
  proxy_components/mock-engine-store/src/mock_cluster/v1/cluster.rs
  proxy_components/mock-engine-store/src/mock_cluster/v1/server.rs
  proxy_components/proxy_server/src/run.rs
  proxy_scripts/ci_check.sh
  proxy_tests/proxy/shared/server_cluster_test.rs
  src/config/mod.rs
  src/server/config.rs
  src/server/metrics.rs
  src/server/server.rs
  src/server/service/kv.rs
  src/server/service/mod.rs
  src/storage/mvcc/reader/reader.rs
  src/storage/txn/actions/prewrite.rs
  src/storage/txn/commands/prewrite.rs
  tests/failpoints/cases/test_kv_service.rs
  tests/failpoints/cases/test_server.rs
Labels: size/XXL, approved, lgtm, tide/merge-method-merge

#381 Fix readme.md and README.md conflicts under MacOS
  .github/workflows/pr-ci.yml
  README-tikv.md
  README.md
  proxy_components/proxy_server/src/setup.rs
  readme.md
Labels: size/XXL, approved, lgtm
