Repository pingcap/tidb-engine-ext, pull requests merged in 2025-02, with the labels that each got.

#419 Limit proxy's memory from TiFlash's side (#408)
  proxy_components/proxy_server/src/config.rs
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_scripts/ci_check.sh
  proxy_tests/proxy/shared/config.rs
  proxy_tests/proxy/shared/store.rs
Labels: size/L

#420 Specify extra store labels by param `--labels`
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_tests/proxy/shared/config.rs
  proxy_tests/proxy/shared/fast_add_peer/fp.rs
Labels: size/XL, approved, lgtm

#406 CP: Fix ps_engine.raftlog unset under default raft-engine dir (#404) to release-8.1
  proxy_components/proxy_server/src/run.rs
  proxy_scripts/ci_check.sh
Labels: size/S

#421 Specify extra store labels by param `--labels` (#420) (release-8.5)
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_tests/proxy/shared/config.rs
  proxy_tests/proxy/shared/fast_add_peer/fp.rs
Labels: size/XL, approved, lgtm

#424 Limit proxy's memory from TiFlash's side (#408)
  Makefile
  proxy_components/proxy_server/src/config.rs
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_scripts/ci_check.sh
  proxy_tests/proxy/shared/config.rs
  proxy_tests/proxy/shared/store.rs
Labels: size/L

#422 Specify extra store labels by param `--labels` (#420) (release-8.1)
  proxy_components/proxy_server/src/proxy.rs
  proxy_components/proxy_server/src/setup.rs
  proxy_scripts/ci_check.sh
  proxy_tests/proxy/shared/config.rs
Labels: size/XL

#426 FFI: Use CppStrWithView as the return type of fn_get_lock_by_key
  gen-proxy-ffi.sh
  gen-proxy-ffi/src/lib.rs
  proxy_components/mock-engine-store/src/mock_store/mock_engine_store_server.rs
  proxy_components/proxy_ffi/src/engine_store_helper_impls.rs
  proxy_components/proxy_ffi/src/interfaces.rs
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/@version
  raftstore-proxy/ffi/src/RaftStoreProxyFFI/ProxyFFI.h
Labels: size/M, approved, lgtm
